[package]
name = "fafnir"
version = "0.1.0"
authors = ["wgjak47"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap  = "2.33.0"
git2 = "0.10"
fs_extra = "1.1.0"
failure = "0.1.5"
shellexpand = "1.1.0"
dirs = "2.0"